### PR TITLE
Minor bug fix in overflow check 

### PR DESCRIPTION
**Pull request by ramSeraph**

### CODE REVIEW

**Comment by bdon** [comment]
Does this have any effect on the program's behavior?

This part of the code is adapted from https://github.com/mapbox/node-fontnik so I'd prefer to keep it matching.

**Comment by ramSeraph** [comment]
I think the overflow checks are just there to be on the safe side and are rarely going to come into play.  So, the question of whether they have an affect on program behaviour is hard to answer. 

I understand wanting to keep parity with node-fontnik. 

I might have more changes coming here for complex text rendering.. this was just an unrelated bugfix i found along the way, which i didn't want to bundle with the other changes.

**Comment by ramSeraph** [comment]
Regarding the other planned changes, ofcourse, they will be discussed before even attempting them.

**Comment by bdon** [comment]
Thanks!

**Comment by ramSeraph** [comment]
Thank you :)

FWIW, I think this repo is now the new and better node-fontnik. Great job with one more problem in the mapping space :)

**Pull request merged**
